version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - '/app/mysql/data:/var/lib/mysql'

  docserver:
    image: onlyoffice/documentserver-de
    restart: always
    environment:
      JWT_ENABLED: 'true'
      JWT_SECRET: '123456'
      DB_TYPE: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PWD: '123456'
    ports:
      - '8071:80'
      - '443:443'
    volumes:
      - '/app/onlyoffice/Data:/var/www/onlyoffice/Data'
      - '/app/onlyoffice/logs:/var/log/onlyoffice'
