version: '3'

services:
  db:
    image: mysql:5.7.16
    ports:
      - 3306:3306
    volumes:
      - /app/mysql/sql:/app/sql
      - /app/mysql/mysql_data:/var/lib/mysql
      # - ./rdic.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - MYSQL_INITDB_EXTRA_ARGS=--explicit_defaults_for_timestamp
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    healthcheck:
      test: [CMD-SHELL, 'curl --silent 127.0.0.1:3306 >/dev/null || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3

  docserver:
    image: onlyoffice/documentserver:latest
    restart: always
    command: ./script/setEnv.sh
    environment:
      JWT_ENABLED: 'true'
      JWT_SECRET: '123456'
      DB_TYPE: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PWD: '123456'
    ports:
      - '8071:80'
      - '443:443'
    volumes:
      - '/app/onlyoffice/Data:/var/www/onlyoffice/Data'
      - '/app/onlyoffice/logs:/var/log/onlyoffice'
